<?php
namespace tg\controllers;

use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * Site controller
 */
class SiteController extends Controller
{

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'hook'  =>  [
                'class' =>  'tg\actions\WebHookAction'
            ],
            'set'  =>  [
                'class' =>  'tg\actions\SetAction'
            ]
        ];
    }


    public function beforeAction($action)
    {
        if($action->id == 'hook'){
            $this->enableCsrfValidation = false;
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * Displays homepage.
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionIndex()
    {
        throw new NotFoundHttpException();
    }

}
