<?php
namespace backend\controllers;

use common\models\AdminToken;
use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if(\Yii::$app->session->get('adminTgAuthToken', false) == false){
            \Yii::$app->session->set('adminTgAuthToken', \Yii::$app->security->generateRandomString(64));
        }

        \Yii::trace(\Yii::$app->session->get('adminTgAuthToken', false));

    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        return $this->render('login');
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        $authToken = \Yii::$app->session->get('tgAuthToken', false);

        if(Yii::$app->user->logout()){
            AdminToken::deleteAll(['token' => $authToken]);
            \Yii::$app->session->remove('tgAuthToken');
        }

        return $this->goHome();
    }
}
