<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "feedbacks".
 *
 * @property integer $id
 * @property integer $created
 * @property integer $userId
 * @property string $username
 * @property string $message
 * @property integer $viewed
 * @property bool       $archived
 */
class Feedback extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'feedbacks';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['created'], 'required'],
            [['created', 'userId', 'viewed', 'archived'], 'integer'],
            [['username', 'message'], 'string'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'created' => 'Created',
            'userId' => 'User ID',
            'username' => 'Username',
            'message' => 'Message',
            'viewed' => 'Viewed',
            'archived' => 'Archived',
        ];
    }

    public function beforeSave($insert)
    {
        if($this->isNewRecord){
            $this->created = time();
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
