<?php
/**
 * Created by PhpStorm.
 * User: bobroid
 * Date: 6/29/17
 * Time: 11:35 PM
 */

namespace backend\models;


use yii\base\Model;
use yii\web\UploadedFile;

class GetTagsForm extends Model
{

    /**
     * @var UploadedFile
     */
    public $track;
    public $hahaha;

    public $fileHash;

    public function rules()
    {
        return [
            [['track'], 'file', 'skipOnEmpty' => false, 'extensions' => 'mp3']
        ];
    }

    public function load($data, $formName = null)
    {
        $loaded = parent::load($data, $formName); // TODO: Change the autogenerated stub

        $this->track = UploadedFile::getInstance($this, 'track');

        return $loaded;
    }

    public function getTags(){
        $filePath = \Yii::getAlias('@web/tmp').'/'.$this->track->baseName.'.'.$this->track->extension;

        $this->track->saveAs($filePath);

        $this->fileHash = hash_file('sha256', $filePath);

        $getID3 = new \getID3;
        $fileInfo = $getID3->analyze($filePath);

        if(file_exists($filePath)){
            unlink($filePath);
        }

        return $fileInfo;
    }

}